name: Run Tests

on: [ 'push', 'pull_request' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.4 ]
        laravel: [ 11.*, 10.* ]
        stability: [ prefer-stable ]
        include:
          - laravel: 11.*
            testbench: 9.*
            carbon: ^2.63
          - laravel: 10.*
            testbench: 8.*
            carbon: ^2.63
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update
          composer require --dev "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: composer test --ci

      # Failure Notification
      - name: Notify on Failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
               "content": "🚨 Workflow **failed** for **${{ github.repository }}**!",
               "embeds": [
                 {
                   "title": "Workflow Failure (PHP ${{ matrix.php }})",
                   "description": "Branch: `${{ github.ref_name }}`\nTriggeredBy: `${{ github.triggering_actor}}`\nCommit: `${{ github.sha}}`",
                   "color": 16711680
                 }
               ]
             }' \
          ${{ secrets.DISCORD }}

      # Success Notification
      - name: Notify on Success
        if: success() && always()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "content": "✅ Workflow **succeeded** for **${{ github.repository }}**!",
                "embeds": [
                  {
                    "title": "Success (PHP ${{ matrix.php }})",
                    "description": "Branch: `${{ github.ref_name }}`\nTriggeredBy: `${{ github.triggering_actor}}`\nCommit: `${{ github.sha}}`",
                    "color": 65280
                  }
                ]
              }' \
          ${{ secrets.DISCORD }}